In [1]:
import pyemma.msm as msm
import numpy as np
import matplotlib
matplotlib.use('pdf')
import pyemma.plots as mplt
import matplotlib.pyplot as plt
import tables

In [2]:
from msmbuilder.io import save_meta,load_meta

In [3]:
cd /home/disk2/wdd/PDZ/12concentration_MSM_Q0930/kcenters_micro400lag400_2

/home/disk2/wdd/PDZ/12concentration_MSM_Q0930/kcenters_micro400lag400_2


In [4]:
clustered_trajs=load_meta('clustered_trajs.pickl')

In [5]:
len(clustered_trajs)

756

In [6]:
msm_lag = 400
m400 = msm.bayesian_markov_model(clustered_trajs, msm_lag,dt_traj='100 ps')

Sampling MSMs: 100% (100/100) [####################################] eta 00:01 /

In [7]:
m400.pi

array([  1.02650918e-01,   1.95902480e-03,   8.40088246e-06,
         9.80132013e-06,   4.15501349e-06,   1.41235976e-06,
         1.23429792e-06,   2.63681988e-02,   2.26087901e-04,
         1.01316378e-03,   1.43792697e-04,   1.52917016e-04,
         4.33595862e-03,   1.38919144e-05,   4.12709244e-04,
         1.26088092e-06,   3.04897677e-04,   9.01625575e-06,
         1.15185203e-03,   9.59073352e-05,   2.69022052e-04,
         5.70725479e-06,   3.42344972e-04,   6.82124092e-06,
         1.00168708e-04,   1.38038070e-03,   1.19426128e-05,
         1.64229857e-06,   7.33030008e-06,   1.92170101e-04,
         1.15918880e-04,   1.69877088e-06,   8.59774765e-04,
         5.01244972e-05,   5.66189895e-06,   1.43231061e-03,
         7.59067648e-06,   1.63101296e-04,   2.08786098e-04,
         3.42746567e-04,   3.67147036e-05,   2.73630815e-04,
         1.22662931e-04,   3.42489378e-04,   1.20386493e-04,
         2.86891311e-05,   1.69165379e-03,   1.19297356e-04,
         3.45669449e-04,

In [11]:
msm_lag = 400
m400_mlh=msm.estimate_markov_model(clustered_trajs, msm_lag)

In [8]:
cluster_centers=np.loadtxt('cluster_center_kcenters400.cs')

In [55]:
def MapMacro(x,y):
    if x<=0.13 and y>=0.86:
        return 0
    elif x<=0.13 and y>=0.01 and y<0.86:
        return 1
    elif x<=0.13 and y<0.01:
        return 2
    elif x>0.13 and y>=0.01:
        return 3
    elif x>0.13 and y<0.01:
        return 4

In [56]:
wf=open('mapmacro2.cs','w')
i=0
for cc in cluster_centers:
    wf.write(str(i)+'    '+str(MapMacro(cc[0],cc[1]))+'\n')
    i+=1
wf.close()

In [57]:
mapmacro=np.loadtxt('mapmacro2.cs')

In [93]:
mapmacro=np.loadtxt('mapmacro2.cs')
L0=[]
L1=[]
L2=[]
L3=[]
L4=[]
for mm in mapmacro:
    if mm[1]==0:
        L0.append(int(mm[0]))
    elif mm[1]==1:
        L1.append(int(mm[0]))
    elif mm[1]==2:
        L2.append(int(mm[0]))
    elif mm[1]==3:
        L3.append(int(mm[0]))
    elif mm[1]==4:
        L4.append(int(mm[0]))

In [94]:
L0=np.array(L0)
L1=np.array(L1)
L2=np.array(L2)
L3=np.array(L3)
L4=np.array(L4)

In [72]:
L24=np.array([0,  34, 107, 361, 373,  7,  36,  81, 114, 185, 186, 213, 265, 267, 320])

In [48]:
L24=np.array([0,  34,  7,  36,  81, 114, 185, 213])

In [100]:
L3

array([  2,   4,   6,   8,   9,  10,  11,  13,  14,  15,  16,  18,  19,
        20,  22,  23,  24,  25,  26,  29,  30,  31,  32,  35,  38,  40,
        41,  42,  43,  44,  45,  48,  49,  53,  55,  57,  58,  60,  61,
        63,  67,  68,  70,  71,  72,  73,  74,  75,  76,  78,  80,  82,
        83,  84,  87,  88,  90,  92,  93,  95,  96,  97, 100, 101, 103,
       104, 105, 106, 108, 109, 110, 112, 115, 116, 117, 118, 119, 124,
       125, 126, 127, 129, 132, 133, 135, 136, 137, 138, 139, 141, 142,
       143, 146, 147, 148, 149, 150, 153, 154, 155, 156, 158, 159, 161,
       162, 163, 164, 167, 171, 174, 175, 177, 178, 179, 180, 182, 183,
       184, 187, 188, 189, 190, 192, 194, 196, 198, 199, 200, 201, 203,
       204, 205, 206, 207, 208, 211, 212, 216, 217, 218, 219, 220, 221,
       224, 226, 227, 228, 231, 232, 235, 236, 238, 239, 241, 242, 243,
       244, 245, 249, 250, 252, 253, 254, 255, 256, 257, 260, 261, 263,
       264, 270, 274, 276, 277, 278, 279, 280, 283, 285, 286, 28

In [36]:
from pyemma.msm import tpt
tpt1=tpt(m400,L24,L0)

In [37]:
tpt1.mfpt

20216480.455433547

In [54]:
tpt1.rate*100

4.7439560059795447e-06

In [97]:
m400_mlh2=msm.estimate_markov_model(clustered_trajs, msm_lag)

In [73]:
from pyemma.msm import tpt
tpt24_0=tpt(m400_mlh2,L24,L0)

In [74]:
tpt24_0.mfpt

210794.53492813694

In [61]:
tpt0_24=tpt(m400_mlh2,L0,L24)

In [63]:
tpt0_24.mfpt

57439.136879732752

In [101]:
tpt24_1=tpt(m400_mlh2,L24,L1)
tpt24_3=tpt(m400_mlh2,L24,L3)
tpt10=tpt(m400_mlh2,L1,L0)
tpt01=tpt(m400_mlh2,L0,L1)
tpt30=tpt(m400_mlh2,L3,L0)
tpt03=tpt(m400_mlh2,L0,L3)

In [102]:
print tpt24_1.mfpt
print tpt24_3.mfpt
print tpt10.mfpt
print tpt01.mfpt
print tpt30.mfpt
print tpt03.mfpt

32502.6877539
8272.4402002
17192.4332655
4732.8948529
18738.5855799
3892.37426342


In [62]:
tpt24=tpt(m400_mlh2,L2,L4)
tpt42=tpt(m400_mlh2,L4,L2)

In [63]:
print tpt24.mfpt
print tpt42.mfpt

812.644934914
2745.49895292


In [71]:
population2=0
for i in L2:
    population2+=m400_mlh2.pi[i]

In [72]:
population4=0
for i in L4:
    population4+=m400_mlh2.pi[i]

In [73]:
print population2
print population4

0.161668611859
0.542462382593


In [61]:
from pyemma.msm import tpt
tpt13=tpt(m400_mlh,L1,L3)
tpt31=tpt(m400_mlh,L3,L1)

NameError: name 'm400_mlh' is not defined

In [14]:
print tpt13.mfpt
print tpt31.mfpt

4030.87869469
14051.1525774


In [54]:
m400_mlh2.pcca?

In [60]:
tpt21=tpt(m400_mlh2,L2,L1) #/10000
tpt12=tpt(m400_mlh2,L1,L2)
print tpt21.mfpt
print tpt12.mfpt

32449.4015407
12211.4150265


In [71]:
tpt34=tpt(m400_mlh2,L3,L4) #/10000
tpt43=tpt(m400_mlh2,L4,L3)
print tpt34.mfpt
print tpt43.mfpt

3472.54840273
8262.8635501


In [80]:
tpt24=tpt(m400_mlh2,L2,L4) #/10000
tpt42=tpt(m400_mlh2,L4,L2)
print tpt24.mfpt
print tpt42.mfpt

812.644934914
2745.49895292


In [81]:
tpt20=tpt(m400_mlh2,L2,L0) #/10000
tpt40=tpt(m400_mlh2,L4,L0)
print tpt20.mfpt
print tpt40.mfpt

210801.487273
210793.114599


In [77]:
tpt21=tpt(m400_mlh2,L2,L1)
print tpt21.mfpt

32449.4015407


In [85]:
def MapMacro2(x,y):
    if x<=0.13 and y>=0.86:
        return 0
    elif x>=0.08 and x<0.13 and y>=0.2 and y<0.3:
        return 1
    elif x>=0.13 and x<0.18 and y>=0.2 and y<0.3:
        return 2
    elif x>=0.18 and x<0.23 and y>=0.2 and y<0.3:
        return 3
    elif x>=0.23 and x<0.28 and y>=0.2 and y<0.3:
        return 4
    elif x>=0.28 and x<0.33 and y>=0.2 and y<0.3:
        return 5
    else:
        return 6

In [86]:
wf=open('mapmacro2_test.cs','w')
i=0
for cc in cluster_centers:
    wf.write(str(i)+'    '+str(MapMacro2(cc[0],cc[1]))+'\n')
    i+=1
wf.close()

In [103]:
mapmacro=np.loadtxt('mapmacro2_test.cs')
L0=[]
L1=[]
L2=[]
L3=[]
L4=[]
L5=[]
for mm in mapmacro:
    if mm[1]==0:
        L0.append(int(mm[0]))
    elif mm[1]==1:
        L1.append(int(mm[0]))
    elif mm[1]==2:
        L2.append(int(mm[0]))
    elif mm[1]==3:
        L3.append(int(mm[0]))
    elif mm[1]==4:
        L4.append(int(mm[0]))
    elif mm[1]==5:
        L5.append(int(mm[0]))

In [92]:
tpt10=tpt(m400_mlh2,L1,L0) #/10000
tpt20=tpt(m400_mlh2,L2,L0)
tpt30=tpt(m400_mlh2,L3,L0) #/10000
tpt40=tpt(m400_mlh2,L4,L0)
tpt50=tpt(m400_mlh2,L5,L0) #/10000
print tpt10.mfpt
print tpt20.mfpt
print tpt30.mfpt
print tpt40.mfpt
print tpt50.mfpt

184395.782695
184646.999044
183016.250463
188496.569171
192898.619753


In [105]:
tpt21=tpt(m400_mlh2,L2,L1) #/10000
tpt31=tpt(m400_mlh2,L3,L1) #/10000
tpt41=tpt(m400_mlh2,L4,L1) #/10000
tpt51=tpt(m400_mlh2,L5,L1) #/10000
print tpt21.mfpt
print tpt31.mfpt
print tpt41.mfpt
print tpt51.mfpt

206722.725678
223853.047794
231357.52027
235772.342884


In [2]:
import numpy as np
a=np.array([300,400,60])

In [4]:
b=np.array([2,0,1])

In [5]:
a[b]

array([ 60, 300, 400])