In [4]:
cd /home/disk2/wdd/PDZ/12concentration

/home/disk2/wdd/PDZ/12concentration


In [8]:
import MDAnalysis as mda
from MDAnalysis.analysis import contacts_sss

In [4]:
mda.__file__

'/software/anaconda2/envs/msmb/lib/python2.7/site-packages/MDAnalysis/__init__.pyc'

In [5]:
contacts.__file__

'/software/anaconda2/envs/msmb/lib/python2.7/site-packages/MDAnalysis/analysis/contacts.pyc'

In [10]:
chain=['A','B','C','D','E','F','G','H','I','J','K','L','M']
t_ref=mda.Universe('12con_ref.pdb',top='12con_ref.pdb')
group1=t_ref.select_atoms('segid A and (name C* or name N* or name O* or name S*)')
trjname="fit1_1000ns.pdb"
u=mda.Universe("begin.pdb",trjname)
for i in range(4,5):
    filename='fit'+str(nt)+'_chain'+str(i)+'_Q_heavyatoms_test.cs'
    wf=open(filename,'w')
    sel2='segid '+chain[i]+' and (name C* or name N* or name O* or name S*)'
    print i
    group2=t_ref.select_atoms(sel2)
    nc=contacts_sss.Contacts(u,selection=("segid A and (name C* or name N* or name O* or name S*)",sel2),refgroup=(group1,group2),method='soft_cut')
    nc.run()
    bound=nc.timeseries[:,1]
    print bound
    for b in bound:
        wf.write(str(b)+'\n')
    wf.close()

4
[  5.42588541   4.01076169   3.1574986    4.06650856   4.09245543
   3.44595059   3.81715536   4.559715     3.61173058   3.04279282
   3.35682525   4.4262997    4.12379676   3.93469277   4.37715919
   4.3850328    4.14508135   4.11817779   4.68569181   4.74144281
   3.82444606   3.88118884   4.21129584   2.81298806   5.25262397
   6.09505915   4.82147726   4.95146916   5.82863856   5.2692142
   6.92776842   5.68229811   4.85718057   4.98438706   4.7311523
   4.25094202   4.37503365   3.93636905   4.44132902   4.67855592
   4.8644014    6.8834709    4.25667638   3.40575942   3.39447948
   3.94694911   3.45130358   4.47694251   4.78866578   3.92002722
   4.69676661   5.88773363   4.65499042   5.92707226   4.41353567
   3.41300804   4.75947846   4.22247722   9.31189476   4.78882665
   3.95330268   4.8244657    4.07643047   3.37949897   4.62482609
   4.75994527   4.75039279   3.7361716    3.41589102   4.0759174
   4.37041853   4.2084801    4.83009159   5.86267544   6.61894603
   7.134843

In [11]:
import mdtraj as md
import numpy as np

In [12]:
t_ref=md.load('12con_ref.pdb',top='12con_ref.pdb')

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/mdtraj/core/trajectory.py:419: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')


In [13]:
pdz_heavy_atoms=[atom.index for atom in t_ref.topology.atoms if atom.element.symbol is not 'H'and atom.index <1738]

In [14]:
peptide_heavy_atoms=[atom.index for atom in t_ref.topology.atoms if atom.element.symbol is not 'H'and (atom.residue.chain.index==4)]

In [15]:
atom_pairs=[]
temp=[]
for h in pdz_heavy_atoms:
    for hh in peptide_heavy_atoms:
        temp.append(h)
        temp.append(hh)
        atom_pairs.append(temp)
        temp=[]

In [16]:
distances_ref=md.compute_distances(t_ref,atom_pairs=atom_pairs)

In [20]:
native_contacts_index=[]
for i in range(len(atom_pairs)):
    if distances_ref[0][i]<=0.45:
        native_contacts_index.append(atom_pairs[i])

In [21]:
distances_ref[0]

array([ 3.27386737,  3.27077889,  3.19752216, ...,  2.70607734,
        2.6261127 ,  2.82912445], dtype=float32)

In [22]:
t1_4=md.load('fit1_1000ns.pdb',top='12con_ref.pdb')

In [23]:
distances1_4=md.compute_distances(t1_4,atom_pairs=native_contacts_index)

In [24]:
distances1_4

array([[ 0.54258841,  0.40107587,  0.31575   ,  0.40665126,  0.40924561,
         0.34459561,  0.38171619,  0.45597178,  0.36117274,  0.3042793 ,
         0.33568293,  0.44262946,  0.41237959,  0.39346927,  0.43771565,
         0.43850294,  0.41450801,  0.41181779,  0.46856904,  0.47414449,
         0.38244489,  0.38811854,  0.42112947,  0.28129891,  0.52526248,
         0.60950625,  0.48214734,  0.4951466 ,  0.58286357,  0.52692115,
         0.69277674,  0.5682295 ,  0.48571798,  0.49843854,  0.47311538,
         0.42509395,  0.43750286,  0.39363691,  0.44413295,  0.4678559 ,
         0.48644024,  0.68834728,  0.42566764,  0.34057599,  0.33944803,
         0.39469481,  0.34513029,  0.44769409,  0.47886616,  0.39200243,
         0.46967643,  0.58877289,  0.4654983 ,  0.59270734,  0.44135344,
         0.3413001 ,  0.47594726,  0.42224729,  0.93118948,  0.47888282,
         0.3953298 ,  0.48244649,  0.40764308,  0.33794942,  0.46248233,
         0.47599462,  0.47503909,  0.37361732,  0.3

In [25]:
distances_ref=md.compute_distances(t_ref,atom_pairs=native_contacts_index)

In [26]:
distances_ref

array([[ 0.43595996,  0.4087967 ,  0.43681681,  0.30117252,  0.41293582,
         0.41170648,  0.32355836,  0.43858048,  0.34634793,  0.34866175,
         0.27027941,  0.42032468,  0.3965866 ,  0.37569791,  0.43773288,
         0.42749739,  0.42555389,  0.39668378,  0.43603438,  0.36943746,
         0.42859063,  0.36833823,  0.27396917,  0.38863978,  0.3400431 ,
         0.3715173 ,  0.39680976,  0.41438395,  0.31339422,  0.41139054,
         0.42597884,  0.43356541,  0.35126355,  0.34637272,  0.38495073,
         0.41484219,  0.37457985,  0.41161272,  0.44718692,  0.3931427 ,
         0.36402646,  0.42168826,  0.40428448,  0.34149817,  0.3995122 ,
         0.35791898,  0.27447769,  0.36064532,  0.38686046,  0.31860006,
         0.39355072,  0.34118611,  0.42701161,  0.43868104,  0.40684754,
         0.30681917,  0.44861561,  0.41169041,  0.41954383,  0.42139277,
         0.3531926 ,  0.43562597,  0.44991657,  0.41330636,  0.43848151,
         0.39522523,  0.39425114,  0.43827611,  0.4

In [27]:
def soft_cut_q1(r, r0, beta=5.0, lambda_constant=1.8):
    r = np.asarray(r)
    r0 = np.asarray(r0)
    result = 1/(1 + np.exp(beta*(r - lambda_constant * r0)))

    return result.sum() / len(r0)

In [30]:
soft_cut_q1(distances1_4[0]*10,distances_ref[0]*10)

0.92422225387008106