In [1]:
cd /home/dongdong/SCR/cluster

/scratch/gpfs/dongdong/cluster


In [35]:
import numpy as np
import sklearn.cluster as cluster
from sklearn.preprocessing import StandardScaler

In [8]:
data=np.loadtxt('plm.out')[:,1:]

In [36]:
X = StandardScaler().fit_transform(data)

In [82]:
data*np.array([10,1,5,1,1,1])

array([[  6.83796 ,   9.438016,   7.50755 ,   7.899804,  13.265936,
          5.630607],
       [  6.95407 ,   8.21267 ,   7.89403 ,   8.854853,  13.259849,
          6.313131],
       [  6.90346 ,   8.76349 ,   8.01008 ,   8.621128,  13.453388,
          4.313604],
       ..., 
       [  7.12295 ,   7.179439,   6.57648 ,   9.991641,  12.323055,
          6.897952],
       [  6.9263  ,   7.520946,   6.99803 ,   9.673736,  12.16762 ,
          6.376927],
       [  6.67011 ,   7.441864,   7.586245,   9.408931,  12.26711 ,
          5.984017]])

In [64]:
data

array([[  0.683796,   9.438016,   1.50151 ,   7.899804,  13.265936,
          5.630607],
       [  0.695407,   8.21267 ,   1.578806,   8.854853,  13.259849,
          6.313131],
       [  0.690346,   8.76349 ,   1.602016,   8.621128,  13.453388,
          4.313604],
       ..., 
       [  0.712295,   7.179439,   1.315296,   9.991641,  12.323055,
          6.897952],
       [  0.69263 ,   7.520946,   1.399606,   9.673736,  12.16762 ,
          6.376927],
       [  0.667011,   7.441864,   1.517249,   9.408931,  12.26711 ,
          5.984017]])

In [58]:
cls = cluster.AgglomerativeClustering(n_clusters = None,linkage='average',distance_threshold=2)
cls.fit(X)

AgglomerativeClustering(affinity='euclidean', compute_full_tree='auto',
                        connectivity=None, distance_threshold=2,
                        linkage='average', memory=None, n_clusters=None,
                        pooling_func='deprecated')

In [59]:
len(set(cls.labels_))

29

In [84]:
def cv_dist (a, b) :
    diff = a - b
    angle_pbc_range = len(diff)
    if cv_dih_dim is not None :
        angle_pbc_range = cv_dih_dim
    for ii in range(len(diff)) :
        value = diff[ii]
        if ii < angle_pbc_range :
            if value < -np.pi :
                value += 2 * np.pi
            elif value >= np.pi :
                value -= 2 * np.pi
        diff[ii] = value
    return np.linalg.norm(diff)

def mk_dist (cv) :
    nframe = cv.shape[0]
    dist = np.zeros([nframe, nframe])
    for ii in range(nframe) :
        for jj in range(ii+1, nframe) :
            dist[ii][jj] = cv_dist(cv[ii], cv[jj])
            dist[jj][ii] = dist[ii][jj]
    return dist

def mk_cluster (dist, distance_threshold) :
    cls = cluster.AgglomerativeClustering(n_clusters = None,
                                          linkage='average',
                                          affinity = 'precomputed',
                                          distance_threshold=distance_threshold)
    cls.fit(dist)
    return cls.labels_
def sel_from_cluster (angles, distance_threshold) :
    dist = mk_dist (angles)
    labels = mk_cluster (dist, distance_threshold)
    # make cluster map
    cls_map = []
    for ii in range(len(set(labels))) :
        cls_map.append([])
    for ii in range(len(labels)) :
        cls_idx = labels[ii]
        cls_map[cls_idx].append(ii)
    # randomly select from cluster
    cls_sel = []
    np.random.seed(seed = None)
    for ii in cls_map :
        _ret = np.random.choice(ii, 1)
        cls_sel.append (_ret[0])
    cls_sel.sort()
    return cls_sel


In [87]:
len(set(sel_from_cluster(data*np.array([10,1,5,1,1,1]),2.2)))

16

In [46]:
StandardScaler().fit_transform(xx)

array([[ 1.22474487,  0.        ,  0.        ],
       [ 0.        ,  1.22474487,  1.22474487],
       [-1.22474487, -1.22474487, -1.22474487]])

In [62]:
np.append(np.sin(xx[:,:1]),np.cos(xx[:,1:]),axis=1)

array([[ 0.09983342, -0.83907153,  0.86231887],
       [ 0.        ,  0.0044257 ,  0.89200487],
       [-0.09983342, -0.91113026,  0.03982088]])

In [66]:
def preprocess(data) :
    if cv_dih_dim is not None :
        angle=np.append(np.sin(data[:,:cv_dih_dim]),np.cos(data[:,:cv_dih_dim]),axis=1)
        alldata=np.append(angle,data[:,cv_dih_dim:],axis=1)
    else:
        alldata=data
    return alldata

def mk_cluster (data, distance_threshold) :
    scale_data=StandardScaler().fit_transform(data)
    cls = cluster.AgglomerativeClustering(n_clusters = None,
                                          linkage='average',
                                          distance_threshold=distance_threshold)
    cls.fit(scale_data)
    return cls.labels_

def sel_from_cluster (angles, distance_threshold) :
    labels = mk_cluster (preprocess(angles), distance_threshold)
    # make cluster map
    cls_map = []
    for ii in range(len(set(labels))) :
        cls_map.append([])
    for ii in range(len(labels)) :
        cls_idx = labels[ii]
        cls_map[cls_idx].append(ii)
    # randomly select from cluster
    cls_sel = []
    np.random.seed(seed = None)
    for ii in cls_map :
        _ret = np.random.choice(ii, 1)
        cls_sel.append (_ret[0])
    cls_sel.sort()
    return cls_sel

In [75]:
cv_dih_dim=0
len(sel_from_cluster(data,2.4))

17

In [76]:
data2=np.loadtxt('plm2.out')[:,1:]

In [77]:
len(sel_from_cluster(data2,2.4))

22

In [83]:
data2

array([[  0.510996,  12.772394,   2.396522,   8.323615,  10.826641,
          5.33694 ],
       [  0.502781,  12.120231,   2.703766,   7.998907,  10.511305,
          4.407982],
       [  0.506237,  11.826582,   2.474721,   7.789598,  10.820844,
          4.54347 ],
       ..., 
       [  0.514464,  12.489858,   3.082681,   8.019504,  10.314521,
          5.144549],
       [  0.52025 ,  12.087608,   2.705621,   7.91894 ,  10.429593,
          4.560676],
       [  0.517552,  12.692544,   2.94839 ,   7.74699 ,  10.087374,
          4.91584 ]])

In [88]:
len(set(sel_from_cluster(data2*np.array([10,1,5,1,1,1]),2.2)))

8