In [1]:
import pyemma.msm as msm
import numpy as np
import matplotlib
matplotlib.use('pdf')
import pyemma.plots as mplt
import matplotlib.pyplot as plt
import tables

In [52]:
cd /home/disk2/wdd/glpf/msm1nsinPore_extend

/home/disk2/wdd/glpf/msm1nsinPore_extend


In [53]:
import glob
import numpy as np
import mdtraj.io as mdio
from msmbuilder.io import save_meta,load_meta
def label(z):
    rangeBin=np.arange(20,70.25,0.25)
    if z>70:
        lab=len(rangeBin)
    else:
        for i in range(len(rangeBin)):
            if z<=rangeBin[i]:
                lab=i
                break
    return lab
allLabel2=[]
files=glob.glob('traj/*.cs')
wf=open('filename2.cs','w')
for ff in files:
    wf.write(str(ff)+'\n')
    data=np.loadtxt(ff)
    dataz=data[:,1]
    lab=[]
    for z in dataz:
        lab.append(label(z))
    lab2=np.array(lab)
    allLabel2.append(lab2)
wf.close()


In [83]:
pwd

u'/home/disk2/wdd/glpf/msm1nsinPore_extend/EMMA'

In [87]:
lagtimes = range(1,20)
its = msm.timescales_msm(allLabel2, lags=lagtimes, nits=20,errors='bayes', n_jobs=-1)
mplt.plot_implied_timescales(its, show_mean=False, ylog=True, dt=0.1, units='ns', linewidth=2)
plt.savefig('impliedtimescales_errorbar.png',dpi=600,bbox_inches='tight') 

estimating BayesianMSM: 100% (19/19) [#############################] eta 00:00 |

AttributeError: 'module' object has no attribute 'savefig'

In [60]:
msm_lag = 10
M = msm.bayesian_markov_model(allLabel2, msm_lag)

Sampling MSMs: 100% (100/100) [####################################] eta 00:01 /

In [88]:
plt.savefig('impliedtimescales_errorbar.png',dpi=600,bbox_inches='tight')

In [90]:
plt.show()

In [65]:
M.metastable_assignments

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [21]:
mplt.plot_cktest(ck, diag=True, figsize=(7,7), layout=(4,2), padding_top=0.1, y01=True, padding_between=0.3, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7f22d2f36e90>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f22d2f36050>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7f22e4294550>]], dtype=object))

In [22]:
plt.savefig('ck-be.png',dpi=600,bbox_inches='tight')

In [16]:
M.pcca(8)

<msmtools.analysis.dense.pcca.PCCA instance at 0x7f46bd2f9638>

In [47]:
len(M.metastable_assignments)

202

In [74]:
from msmbuilder.io import save_meta,load_meta
mapp=M.metastable_assignments
allLabelmacro=[]
for i in range(len(allLabel2)):
    temp=[]
    for j in range(len(allLabel2[i])):
        if allLabel2[i][j]==202:
            temp.append(mapp[201])
        else:
            temp.append(mapp[allLabel2[i][j]])
    temp2=np.array(temp)
    allLabelmacro.append(temp2)
save_meta(allLabelmacro,'allLabelmacro.pickl')

In [73]:
pwd

u'/home/disk2/wdd/glpf/msm1nsinPore_extend/EMMA'

In [51]:
M.metastable_memberships

array([[  6.10767947e-14,   6.69290208e-02,   1.94076644e-02, ...,
          1.14444141e-02,   9.66070540e-13,   7.75380442e-01],
       [  1.18871414e-04,   6.82702038e-02,   1.97224310e-02, ...,
          3.72370873e-02,   1.07580812e-03,   7.52850990e-01],
       [  1.33430841e-04,   6.84426029e-02,   1.97629849e-02, ...,
          4.04724833e-02,   1.21681111e-03,   7.50025661e-01],
       ..., 
       [  8.30622589e-05,   5.62925947e-02,   2.97975029e-04, ...,
          1.51746867e-04,   6.61583834e-01,   4.76571336e-05],
       [  9.25012751e-05,   5.79663384e-02,   3.12007859e-04, ...,
          1.41202034e-04,   6.65966034e-01,   4.30037038e-05],
       [  1.66633050e-04,   7.74463115e-02,   4.68781541e-04, ...,
          3.12119727e-06,   7.20026092e-01,   0.00000000e+00]])

In [44]:
M.metastable_distributions.shape

(8, 202)

In [53]:
ck_memberships=np.array(np.mat(np.eye(202,202,dtype=int)))

In [54]:
ck_memberships

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [56]:
ck_micro = M.cktest(9, memberships=ck_memberships,mlags=4,n_jobs=6)

estimating BayesianMSM: 100% (3/3) [###############################] eta --:-- \

In [57]:
mplt.plot_cktest(ck_micro, diag=True, figsize=(6,5), layout=(3,3), padding_top=0.1, y01=True, padding_between=0.3, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7f22e43df8d0>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f22d38c0b90>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7f22d2d5df10>]], dtype=object))

In [58]:
plt.savefig('ck-micro9.png',dpi=600,bbox_inches='tight')

In [75]:
ck_micro.predictions[3]

array([[  6.51924860e-01,   1.98470250e-02,   1.99209738e-02, ...,
          7.95478818e-07,   7.79879514e-07,   5.90282234e-05],
       [  5.31236947e-01,   1.94790506e-02,   2.01598877e-02, ...,
          2.24232359e-07,   2.23340356e-07,   2.77122359e-05],
       [  5.14908755e-01,   1.94677143e-02,   2.02403296e-02, ...,
          2.07557364e-07,   2.06779222e-07,   2.62021661e-05],
       ..., 
       [  2.34921554e-05,   2.47399989e-07,   2.37144294e-07, ...,
          1.56495991e-02,   1.47091696e-02,   5.12523380e-01],
       [  2.44410156e-05,   2.61496624e-07,   2.50714193e-07, ...,
          1.56093798e-02,   1.47030720e-02,   5.24427803e-01],
       [  5.22658572e-05,   9.16720784e-07,   8.97585540e-07, ...,
          1.53666005e-02,   1.48167290e-02,   6.60837395e-01]])

In [74]:
ck_micro.estimates[3]

array([[  6.64866916e-01,   1.98041239e-02,   1.97138430e-02, ...,
          2.90285524e-07,   1.18265934e-06,   1.88006476e-05],
       [  4.95759577e-01,   2.63852240e-02,   2.90866227e-02, ...,
          7.78632669e-15,   7.40703678e-15,   3.33196889e-05],
       [  4.74268753e-01,   2.79531682e-02,   3.07555916e-02, ...,
          7.80299935e-15,   7.34527603e-15,   2.49726604e-13],
       ..., 
       [  8.51790539e-06,   9.12536796e-15,   9.51690714e-15, ...,
          2.32465596e-02,   2.27212600e-02,   4.72428277e-01],
       [  3.68265216e-05,   9.21412094e-15,   9.50794119e-15, ...,
          2.41115990e-02,   2.26675544e-02,   4.88738116e-01],
       [  1.75799397e-05,   1.24460068e-06,   9.70665546e-15, ...,
          1.50547318e-02,   1.46764070e-02,   6.86829469e-01]])

In [70]:
ck_micro.predictions.shape

(4, 202, 202)

In [77]:
M.pcca(8)

<msmtools.analysis.dense.pcca.PCCA instance at 0x7f22e4342560>

In [79]:
M.metastable_distributions

array([[  6.03153683e-13,   4.38567373e-05,   5.09786416e-05, ...,
          2.77754587e-05,   2.91479308e-05,   1.85846559e-03],
       [  9.13496633e-02,   3.48121482e-03,   3.61409267e-03, ...,
          2.60165378e-03,   2.52450718e-03,   1.19380901e-01],
       [  4.03816880e-02,   1.53312931e-03,   1.59090417e-03, ...,
          2.09940787e-05,   2.07150026e-05,   1.10159849e-03],
       ..., 
       [  1.48453769e-02,   1.80459816e-03,   2.03113038e-03, ...,
          6.66535294e-06,   5.84449345e-06,   4.57257160e-06],
       [  6.03158138e-13,   2.50936777e-05,   2.93917745e-05, ...,
          1.39866270e-02,   1.32673045e-02,   5.07705914e-01],
       [  4.32905838e-01,   1.57034390e-02,   1.62007459e-02, ...,
          9.00974030e-07,   7.66112813e-07,   0.00000000e+00]])

In [80]:
hmm=M.coarse_grain(8)

05-06-18 17:11:48 pyemma.msm.estimators.bayesian_msm.BayesianMSM[0] WARNING  Requested coarse-grained model with 8 metastable states at lag=10.The ratio of relaxation timescales between 8 and 9 states is only 1.03081393049 while we recommend at least 1.5. It is possible that the resulting HMM is inaccurate. Handle with caution.


In [81]:
hmm.stationary_distribution

array([ 0.05875921,  0.07829717,  0.06893122,  0.09186817,  0.12461267,
        0.15685981,  0.16237643,  0.25829533])

In [82]:
hmm9=M.coarse_grain(9)

05-06-18 20:00:26 pyemma.msm.estimators.bayesian_msm.BayesianMSM[0] WARNING  Requested coarse-grained model with 9 metastable states at lag=10.The ratio of relaxation timescales between 9 and 10 states is only 1.13691823002 while we recommend at least 1.5. It is possible that the resulting HMM is inaccurate. Handle with caution.


array([ 0.05873388,  0.07826362,  0.05295488,  0.04213205,  0.06647642,
        0.12455948,  0.15643232,  0.162307  ,  0.25814036])

In [84]:
hmm10=M.coarse_grain(10)

In [85]:
hmm10.stationary_distribution

array([ 0.05873426,  0.07826537,  0.05236669,  0.0418224 ,  0.06642131,
        0.08279537,  0.14030819,  0.124561  ,  0.19241593,  0.16230947])

In [86]:
hmm10.transition_matrix

array([[  9.65342191e-001,   3.38335457e-002,   0.00000000e+000,
          9.89242734e-172,   7.76976032e-004,   0.00000000e+000,
          0.00000000e+000,   4.30634445e-005,   0.00000000e+000,
          4.22340432e-006],
       [  2.53903907e-002,   8.89032771e-001,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   8.08628211e-002,   0.00000000e+000,
          4.71401689e-003],
       [  0.00000000e+000,   0.00000000e+000,   9.58523500e-001,
          2.65481329e-002,   5.59087202e-004,   1.43692799e-002,
          1.08971579e-014,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  1.38926598e-171,   0.00000000e+000,   3.32414645e-002,
          9.47092024e-001,   1.96388035e-002,   2.77077216e-005,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  6.87055272e-004,   0.00000000e+000,   4.40785441e-004,
          1.23656386e-002,   9.86506521e-00

In [89]:
hmm10.metastable_assignments

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 9, 9, 9, 9])

In [99]:
hmm10.mfpt(9,7)

163.65955803676255

In [100]:
hmm10.mfpt(7,1)

474.37354225492589

In [101]:
hmm10.mfpt(1,0)

2002.8295122554732

In [102]:
hmm10.mfpt(0,4)

88701.174611238559

In [103]:
hmm10.mfpt(4,3)

5629.5535381738

In [104]:
hmm10.mfpt(9,1)

599.39896260615615

In [107]:
ck_macro10_hmm=hmm10.cktest(mlags=4,n_jobs=6)

05-06-18 21:39:54 pyemma.msm.estimators.maximum_likelihood_hmsm.MaximumLikelihoodHMSM[1] WARNING  Ignored error during estimation: 'BayesianMSM' object has no attribute '_is_estimated'
05-06-18 21:39:55 pyemma.msm.estimators.maximum_likelihood_hmsm.MaximumLikelihoodHMSM[1] WARNING  Ignored error during estimation: 'BayesianMSM' object has no attribute '_is_estimated'
05-06-18 21:39:55 pyemma.msm.estimators.maximum_likelihood_hmsm.MaximumLikelihoodHMSM[1] WARNING  Ignored error during estimation: 'BayesianMSM' object has no attribute '_is_estimated'
estimating MaximumLikelihoodHMSM: 100% (3/3) [#####################] eta --:-- |

In [108]:
mplt.plot_cktest(ck_macro10_hmm, diag=True, figsize=(6,5), layout=(4,3), padding_top=0.1, y01=True, padding_between=0.3, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7f22e43f42d0>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f22d2d5fa50>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7f22d36b5210>]], dtype=object))

In [109]:
plt.savefig('ck-macro10-hmm.png',dpi=600,bbox_inches='tight')

In [110]:
pwd

u'/home/disk2/wdd/glpf/msm1nsinPore_extend/EMMA'

In [113]:
hM = msm.bayesian_hidden_markov_model?

In [7]:
hM = msm.bayesian_hidden_markov_model(allLabel2,10,10)

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/msmtools/analysis/dense/decomposition.py:540: ImaginaryEigenValueWarning: Using eigenvalues with non-zero imaginary part
  warnings.warn('Using eigenvalues with non-zero imaginary part', ImaginaryEigenValueWarning)


Sampling HMSMs: 100% (100/100) [###################################] eta 00:00 /

In [9]:
ck_bhm=hM.cktest(mlags=4,n_jobs=6)

estimating BayesianHMSM: 100% (3/3) [##############################] eta 00:00 /

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/pyemma/util/statistics.py:60: UserWarning: confidence interval for constant data is not meaningful
  warnings.warn('confidence interval for constant data is not meaningful')


In [10]:
mplt.plot_cktest(ck_bhm, diag=True, figsize=(6,5), layout=(4,3), padding_top=0.1, y01=True, padding_between=0.3, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7f47570d4f50>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f45f99c9a90>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7f45f9ada410>]], dtype=object))

In [11]:
plt.savefig('ck-bhm.png',dpi=600,bbox_inches='tight')

In [21]:
hM.pi

array([ 0.05859112,  0.07727644,  0.05123045,  0.04195905,  0.06569449,
        0.08177913,  0.13938719,  0.12497057,  0.19395097,  0.1651606 ])

In [23]:
from msmbuilder.io import save_meta,load_meta

In [24]:
macro8=load_meta('/home/disk2/wdd/glpf/msm1nsinPore_extend/lag10/macro8/Macromsm10_traj.pickl')

In [29]:
msm_lag = 10
macro_MSM = msm.bayesian_markov_model(macro8, msm_lag)

Sampling MSMs: 100% (100/100) [####################################] eta 00:00 \

In [30]:
ck_memberships=np.array(np.mat(np.eye(8,8,dtype=int)))

In [75]:
ck_macro = macro_MSM.cktest(8,mlags=4,n_jobs=6)

estimating BayesianMSM: 100% (3/3) [###############################] eta --:-- -

In [76]:
mplt.plot_cktest(ck_macro, diag=True, figsize=(6,5), layout=(4,2), padding_top=0.1, y01=True, padding_between=0.3, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7f4752d357d0>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7f468cb72e10>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7f45fbcf49d0>]], dtype=object))

In [78]:
plt.savefig('ck-macro8.png',dpi=600,bbox_inches='tight')

In [77]:
pwd

u'/home/disk2/wdd/glpf/msm1nsinPore_extend/EMMA'

In [2]:
mplt.plot_implied_timescales?