In [41]:
import pyemma.msm as msm
import numpy as np
import matplotlib
matplotlib.use('pdf')
import pyemma.plots as mplt
import matplotlib.pyplot as plt
import tables

In [42]:
cd /home/disk2/wdd/glpf/msm1nsinPore_extend

/home/disk2/wdd/glpf/msm1nsinPore_extend


In [77]:
import glob
import numpy as np
import mdtraj.io as mdio
from msmbuilder.io import save_meta,load_meta
def label(z):
    rangeBin=np.arange(20,70.25,0.25)
    if z>70:
        lab=len(rangeBin)
    else:
        for i in range(len(rangeBin)):
            if z<=rangeBin[i]:
                lab=i
                break
    return lab
allLabel2=[]
files=glob.glob('traj/*.cs')
wf=open('filename2.cs','w')
for ff in files:
    wf.write(str(ff)+'\n')
    data=np.loadtxt(ff)
    dataz=data[:,1]
    lab=[]
    for z in dataz:
        lab.append(label(z))
    lab2=np.array(lab)
    allLabel2.append(lab2)
wf.close()


In [78]:
cd EMMA/

/home/disk2/wdd/glpf/msm1nsinPore_extend/EMMA


In [5]:
lagtimes = range(1,20)
its = msm.timescales_msm(allLabel2, lags=lagtimes, nits=20,errors='bayes', n_jobs=-1)
mplt.plot_implied_timescales(its, show_mean=False, ylog=True, dt=10, units='ps', linewidth=2)

estimating BayesianMSM: 100% (19/19) [#############################] eta 00:00 /

In [6]:
plt.savefig('impliedtimescales_errorbar.png',dpi=600,bbox_inches='tight') 

In [143]:
msm.timescal

In [1]:
import matplotlib.font_manager as font_manager
font_path = '/home/disk2/wdd/msm/calibribold.ttf'
font_prop = font_manager.FontProperties(fname=font_path, size=20)
fig = plt.figure(figsize=(5,4))
sub = fig.add_subplot(1,1,1)
mplt.plot_implied_timescales(its, show_mean=False, ylog=True, dt=10, units='ps', linewidth=1.6)
for label in (sub.get_xticklabels() + sub.get_yticklabels()):
    label.set_fontproperties(font_prop)
    label.set_fontsize(16)
plt.xlabel(r'lag time (ps)',fontproperties=font_prop)
plt.ylabel(r'implied timescales (ps)',fontproperties=font_prop)
plt.ylim(1,10000000)
plt.semilogy()
plt.savefig('impliedtimescales_EMMA.png',dpi=600,bbox_inches='tight')
plt.show()

NameError: name 'plt' is not defined

In [137]:
msm_lag = 11
M11 = msm.bayesian_markov_model(allLabel2, msm_lag)

Sampling MSMs: 100% (100/100) [####################################] eta 00:00 -

In [11]:
ck_macro = M.cktest(8,mlags=4,n_jobs=6)

estimating BayesianMSM: 100% (3/3) [###############################] eta 01:29 -

In [12]:
mplt.plot_cktest?

In [53]:
mplt.plot_cktest(ck_macro, diag=True, figsize=(6,5), layout=(4,2), padding_top=0.1, y01=True, padding_between=0.16, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7fbf381e1510>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fbf392d0d50>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7fbf290f49d0>]], dtype=object))

In [54]:
plt.savefig('ck8_EMMA.png',dpi=600,bbox_inches='tight')

In [17]:
ck_memberships=np.array(np.mat(np.eye(202,202,dtype=int)))

In [18]:
ck_micro = M.cktest(9, memberships=ck_memberships,mlags=4,n_jobs=6)

Sampling MSMs: 100% (100/100) [####################################] eta 00:00 \

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/progress_reporter/reporter.py:159: UserWarning: This should not happen. An caller pretended to have achieved more work than registered
  warnings.warn("This should not happen. An caller pretended to have "


estimating BayesianMSM: 100% (3/3) [###############################] eta --:-- \

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/pyemma/util/statistics.py:60: UserWarning: confidence interval for constant data is not meaningful
  warnings.warn('confidence interval for constant data is not meaningful')


In [19]:
mplt.plot_cktest(ck_micro, diag=True, figsize=(6,5), layout=(3,3), padding_top=0.1, y01=True, padding_between=0.2, dt=10, units='ps')
plt.savefig('ck202micro_EMMA.png',dpi=600,bbox_inches='tight')

(<matplotlib.figure.Figure at 0x7fbf39415f50>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fbf394159d0>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7fbf3cd48050>]], dtype=object))

In [126]:
M10.pcca(8)

<msmtools.analysis.dense.pcca.PCCA instance at 0x7f7195acc758>

In [139]:
p0=range(177,202)
p1=range(148,177)
p2=range(127,148)
p3=range(111,127)
p4=range(91,111)
p5=range(63,91)
p6=range(27,63)
p7=range(0,27)
tpt01=tpt(M11,p0,p1)
tpt12=tpt(M11,p1,p2)
tpt23=tpt(M11,p2,p3)
tpt34=tpt(M11,p3,p4)
tpt45=tpt(M11,p4,p5)
tpt56=tpt(M11,p5,p6)
tpt67=tpt(M11,p6,p7)
tpt76=tpt(M11,p7,p6)
tpt65=tpt(M11,p6,p5)
tpt54=tpt(M11,p5,p4)
tpt43=tpt(M11,p4,p3)
tpt32=tpt(M11,p3,p2)
tpt21=tpt(M11,p2,p1)
tpt10=tpt(M11,p1,p0)

In [140]:
print tpt01.rate*100
print tpt12.rate*100
print tpt23.rate*100
print tpt34.rate*100
print tpt45.rate*100
print tpt56.rate*100
print tpt67.rate*100
print tpt76.rate*100
print tpt65.rate*100
print tpt54.rate*100
print tpt43.rate*100
print tpt32.rate*100
print tpt21.rate*100
print tpt10.rate*100

0.490474739287
0.1267930446
0.0226551205047
0.00185399855123
0.0563437723651
0.0305259971593
0.172541359582
0.381826424148
0.0393988251878
0.051013616638
0.00141416193279
0.023046368195
0.0904527889309
0.230013882473


In [138]:
wf=open('Populations_lag11.dat','w')
for h in M11.pi:
    wf.write(str(float(h))+'\n')
wf.close()

M11.pcca(8)
print M11.metastable_assignments

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [24]:
from msmbuilder.io import save_meta,load_meta
mapp=M.metastable_assignments
allLabelmacro=[]
for i in range(len(allLabel2)):
    temp=[]
    for j in range(len(allLabel2[i])):
        if allLabel2[i][j]==202:
            temp.append(mapp[201])
        else:
            temp.append(mapp[allLabel2[i][j]])
    temp2=np.array(temp)
    allLabelmacro.append(temp2)
save_meta(allLabelmacro,'allLabelmacro.pickl')

/software/anaconda2/envs/msmb/lib/python2.7/site-packages/msmbuilder-3.8.0-py2.7-linux-x86_64.egg/msmbuilder/io/io.py:54: BackupWarning: allLabelmacro.pickl exists. Moving it to allLabelmacro.pickl.bak.1
  BackupWarning)


In [28]:
from msmbuilder.io import save_meta,load_meta
allLabelmacro=load_meta('allLabelmacro.pickl')
msm_lag = 8
macro_M = msm.bayesian_markov_model(allLabelmacro, msm_lag)

Sampling MSMs: 100% (100/100) [####################################] eta 00:01 \

In [146]:
print M.timestep_model

8.0 step


In [6]:
macro_M.transition_matrix

array([[  7.13582810e-01,   2.73444354e-01,   1.28762327e-02,
          9.66027969e-05,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  2.16896874e-02,   8.82011340e-01,   1.68787070e-04,
          0.00000000e+00,   9.58869369e-02,   0.00000000e+00,
          2.43248196e-04,   0.00000000e+00],
       [  9.54771184e-04,   1.57784860e-04,   9.60106243e-01,
          3.87812006e-02,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  5.46619304e-06,   0.00000000e+00,   2.95941608e-02,
          9.52094478e-01,   0.00000000e+00,   1.82867892e-02,
          0.00000000e+00,   1.91063318e-05],
       [  0.00000000e+00,   4.77388595e-02,   0.00000000e+00,
          0.00000000e+00,   8.02928331e-01,   0.00000000e+00,
          1.49332809e-01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.80431382e-02,   0.00000000e+00,   8.76107008e-01,
          0.00000000e+00,   1.0

In [8]:
wf=open('Populations.dat','w')
for h in macro_M.pi:
    wf.write(str(float(h))+'\n')
wf.close()
wf=open('tProb.mtx','w')
wf.write('%%MatrixMarket matrix coordinate real general\n%\n')
wf.write(str(len(macro_M.transition_matrix))+' '+str(len(macro_M.transition_matrix[0]))+' '+str(len(macro_M.transition_matrix)*len(macro_M.transition_matrix[0]))+'\n')
for i in range(len(macro_M.transition_matrix)):
    for j in range(len(macro_M.transition_matrix[i])):
        wf.write(str(i+1)+' '+str(j+1)+' '+str(macro_M.transition_matrix[i][j])+'\n')
wf.close()

In [11]:
wf=open('mfpt.dat','w')
for i in range(8):
    for j in range(8):
        wf.write(str(macro_M.mfpt(i,j)*0.01)+'    ')
    wf.write('\n')
wf.close()

In [6]:
matrix = macro_M.transition_matrix
wf=open('matrix.dat','w')
for h in matrix:
    for l in h:
        wf.write(str(l)+'    ')
    wf.write('\n')
wf.close()

In [30]:
matrix =macro_M.count_matrix_full
wf=open('new_count_matrix.dat','w')
new_matrix=np.zeros(shape=(8,8))
new_index=[6,4,1,0,2,3,5,7]
for i in range(8):
    for j in range(8):
        new_matrix[i][j]=matrix[new_index[i]][new_index[j]]
for h in new_matrix:
    for l in h:
        wf.write(str(l)+'    ')
    wf.write('\n')
wf.close()

In [24]:
matrix = macro_M.transition_matrix
wf=open('new_matrix.dat','w')
new_matrix=np.zeros(shape=(8,8))
new_index=[6,4,1,0,2,3,5,7]
for i in range(8):
    for j in range(8):
        new_matrix[i][j]=matrix[new_index[i]][new_index[j]]
for h in new_matrix:
    for l in h:
        wf.write(str(l)+'    ')
    wf.write('\n')
wf.close()

In [25]:
mfpt = np.loadtxt('mfpt.dat')
wf=open('new_mfpt.dat','w')
new_mfpt=np.zeros(shape=(8,8))
new_index=[6,4,1,0,2,3,5,7]
for i in range(8):
    for j in range(8):
        new_mfpt[i][j]=mfpt[new_index[i]][new_index[j]]
for h in new_mfpt:
    for l in h:
        wf.write(str(l)+'    ')
    wf.write('\n')
wf.close()

In [75]:
macro_M.

array([ 0.00467344,  0.05891853,  0.06302687,  0.08259257,  0.11834211,
        0.08370788,  0.29570194,  0.29303665])

In [26]:
6.15651233103+1.44602384349

7.60253617452

In [49]:
1/macro_M.mfpt(5,7)

1.668217859251782e-05

In [33]:
from pyemma.msm import tpt

In [69]:
a=tpt(macro_M,[5],[6])

In [73]:
a.rate*100

0.0015787284983089836

In [71]:
b=tpt(macro_M,[6],[5])

In [74]:
b.rate*100

0.0016844550690756244

In [46]:
lagtimes = range(1,20)
its_macro = msm.timescales_msm(allLabelmacro, lags=lagtimes, nits=7,errors='bayes', n_jobs=-1)
fig = plt.figure(figsize=(5,4))
sub = fig.add_subplot(1,1,1)
mplt.plot_implied_timescales(its_macro, show_mean=False, ylog=True, dt=10, units='ps', linewidth=2.2)
for label in (sub.get_xticklabels() + sub.get_yticklabels()):
    label.set_fontproperties(font_prop)
    label.set_fontsize(16)
plt.xlabel(r'lag time (ps)',fontproperties=font_prop)
plt.ylabel(r'implied timescales (ps)',fontproperties=font_prop)
plt.ylim(1,10000000)
plt.semilogy()
plt.savefig('impliedtimescales_EMMA_macro.png',dpi=600,bbox_inches='tight')
plt.show()

In [50]:
ck_memberships=np.array(np.mat(np.eye(8,8,dtype=int)))
ck_ = macro_M.cktest(8, memberships=ck_memberships,mlags=4,n_jobs=6)

estimating BayesianMSM: 100% (3/3) [###############################] eta --:-- -

In [55]:
mplt.plot_cktest(ck_, diag=True, figsize=(6,5), layout=(4,2), padding_top=0.1, y01=True, padding_between=0.16, dt=10, units='ps')

(<matplotlib.figure.Figure at 0x7fbf28f284d0>,
 array([[<matplotlib.axes._subplots.AxesSubplot object at 0x7fbf28f1db90>,
         <matplotlib.axes._subplots.AxesSubplot object at 0x7fbf30503690>]], dtype=object))

In [56]:
plt.savefig('ck_pcca-macro_EMMA.png',dpi=600,bbox_inches='tight')

In [57]:
plt.scatter?

In [86]:
tpt75=msm.tpt(macro_M,[7],[5])
tpt57=msm.tpt(macro_M,[5],[7])

In [87]:
tpt75.mfpt


284.15493181365429

In [98]:
tpt53=msm.tpt(macro_M,[5],[3])
tpt35=msm.tpt(macro_M,[3],[5])

In [97]:
tpt53.total_flux

0.00018933334415187773

In [99]:
tpt35.total_flux

0.00018933334415186415

In [104]:
tpt75.total_flux

0.0011080963639094326

In [103]:
tpt57.total_flux

0.0011080963639094139

In [110]:
tpt32=msm.tpt(macro_M,[3],[2])
tpt23=msm.tpt(macro_M,[2],[3])

In [111]:
tpt32.total_flux

0.00030592585563429396

In [112]:
tpt20=msm.tpt(macro_M,[2],[0])
tpt02=msm.tpt(macro_M,[0],[2])

In [113]:
tpt20.total_flux

9.161405456456862e-06

In [108]:
tpt01=msm.tpt(macro_M,[0],[1])
tpt10=msm.tpt(macro_M,[1],[0])

In [109]:
tpt01.total_flux

0.00016106093971120079

In [123]:
tpt01.rate-tpt10.rate

8.4985800692739908e-05

In [122]:
tpt02.rate-tpt20.rate

1.9029350598522365e-06

In [117]:
tpt10.rate

0.00028514016452531435

In [124]:
tpt67=msm.tpt(macro_M,[6],[7])

In [127]:
tpt67.rate

1.6682178592514337e-05

In [101]:
rran=range(0.0,0.2,0.01)+np.arange(0.2,0.6,0.02)

In [117]:
rran=(np.arange(0,20)/100.0)

In [119]:
np.arange(0.2,0.6,0.02)

array([ 0.2 ,  0.22,  0.24,  0.26,  0.28,  0.3 ,  0.32,  0.34,  0.36,
        0.38,  0.4 ,  0.42,  0.44,  0.46,  0.48,  0.5 ,  0.52,  0.54,
        0.56,  0.58])