In [1]:
cd /home/dongdong/SCR/PD1

/scratch/gpfs/dongdong/PD1


In [7]:
seq='HHHHGVNAGGWQTCRGSETKQINWDVKRASDGWGRQNDNAALREYGANAGDWQRRRGCEGNQRNWDAKRTGDGWGYCFHHHHHHGVNAGGWQTCRGSETKQINWDVKRASDGWGRQNDNAALREYGANAGDWQRRRGCEGNQRNWDAKRTGDGWGYCFHH'
wf=open('allfasta.fasta','w')
for i in range(1,81):
    wf.write(seq[i-1:i+11]+'\n')
wf.close()

In [10]:
pwd

'/scratch/gpfs/dongdong/PD1'

In [6]:
import re
def replace (file_name, pattern, subst) :
    file_handel = open (file_name, 'r')
    file_string = file_handel.read ()
    file_handel.close ()
    file_string = ( re.sub (pattern, subst, file_string) )
    file_handel = open (file_name, 'w')
    file_handel.write (file_string)
    file_handel.close ()


In [9]:
import mdtraj as md
from contact_map import ContactMap

In [11]:
traj = md.load("pd1_sd.pqr.pdb", top="pd1_sd.pqr.pdb")

/home/dongdong/software/anaconda3/lib/python3.7/site-packages/mdtraj/core/trajectory.py:419: UserWarning: top= kwarg ignored since file contains topology information
  warnings.warn('top= kwarg ignored since file contains topology information')


In [12]:
ContactMap?

In [13]:
topology = traj.topology

In [22]:
chainA=topology.select("chainid == 0 and symbol != 'H'")
chainB=topology.select("chainid == 1 and symbol != 'H'")

In [47]:
frame_contacts = ContactMap(traj[0],query=chainA, haystack=chainA,cutoff=0.5)

In [59]:
source activate py2

SyntaxError: invalid syntax (<ipython-input-59-ac5f6201433f>, line 1)

In [230]:
cd /home/dongdong/SCR/PD1/vs_8_result/PD1/Results_PD1_2

/scratch/gpfs/dongdong/PD1/vs_8_result/PD1/Results_PD1_2


In [219]:
PD1_hot=[75,134,126,84,78,68,128,66]
PD1_hyd=[126,128,134]
PD1_o=[136,139]

In [231]:
rf=open('all_score.txt','r')
wf=open('all_score2.dat','w')
alllines=rf.readlines()

for line in alllines:
    line=line.strip()
    num=int(line.split()[2])
    if num>7:
        wf.write(line+'\n')
wf.close()

In [137]:
dirname='/home/dongdong/SCR/PD1/vs_12_result/PD1/Results_PD1_1'
rf=open(dirname+'sorted.txt','r')
wf=open(dirname+'score_interface.txt','w')
wf2=open(dirname+'score_interface_filter_o.txt','w')
for line in rf.readlines()[1:1501]:
    line=line.strip()
    peptide=line.split()[0]
    score=line.split()[1]
    wf.write(line+'    ')
    interface_name=dirname+'out_'+peptide+'/molecule_1.txt'
    indata=open(interface_name,'r')
    nn=0
    for ii in indata.readlines():
        ii=ii.strip()
        resid=int(ii.split()[1])
        if int(resid) in PD1_o:
            nn+=1
    if nn>1:
        wf2.write(line+'    '+str(nn)+'\n')
    wf.write(str(nn)+'\n')
wf.close()
wf2.close()

In [117]:
cd /home/dongdong/SCR/PD1/3/PD1_results

/scratch/gpfs/dongdong/PD1/3/PD1_results


In [125]:
dataob=open('score_interface_filter.txt','r')
for line in dataob.readlines():
    line=line.strip()
    infor=line.split()
    name=infor[0]+'.pdb'
    print(name)
    os.system('cp docked_pdb/%s %s' %(name,name))

WGY_11.pdb
FHH_13.pdb
WDA_17.pdb
WDA_20.pdb
WDA_29.pdb
WDA_35.pdb
WDA_50.pdb
WDA_7.pdb
WQT_2.pdb
WQT_27.pdb
WQT_35.pdb
REY_31.pdb
REY_35.pdb
WDA_16.pdb
WDA_2.pdb
WDA_28.pdb
WDA_41.pdb
WDA_5.pdb
WQT_13.pdb
WQT_31.pdb
WQT_41.pdb
EYG_11.pdb
EYG_28.pdb
REY_16.pdb
REY_25.pdb
REY_3.pdb
WDA_43.pdb
WDA_8.pdb
WGY_39.pdb
WQT_21.pdb
WQT_28.pdb
WQT_38.pdb
WQT_40.pdb
YCF_44.pdb
EYG_23.pdb
EYG_5.pdb
GWG_19.pdb
GWG_22.pdb
GWG_31.pdb
GWG_33.pdb
GWG_41.pdb
GWG_44.pdb
GWG_4.pdb
GWG_6.pdb
GWG_7.pdb
HHH_11.pdb
REY_45.pdb
WDA_12.pdb
WDA_48.pdb
WQT_12.pdb
WQT_39.pdb
WQT_4.pdb
YCF_24.pdb
YCF_26.pdb
YCF_28.pdb
YCF_31.pdb
YCF_32.pdb
YCF_39.pdb
YCF_43.pdb
YGA_44.pdb
CFH_47.pdb
EYG_18.pdb
EYG_24.pdb
EYG_27.pdb
EYG_34.pdb
EYG_38.pdb
EYG_47.pdb
EYG_48.pdb
GDG_20.pdb
GGW_10.pdb
GGW_33.pdb
GGW_36.pdb
GGW_9.pdb
GWG_11.pdb
GWG_14.pdb
GWG_15.pdb
GWG_1.pdb
GWG_16.pdb
GWG_18.pdb
GWG_21.pdb
GWG_24.pdb
GWG_26.pdb
GWG_27.pdb
GWG_29.pdb
GWG_32.pdb
GWG_37.pdb
GWG_38.pdb
GWG_39.pdb
GWG_40.pdb
GWG_42.pdb
GWG_45.pdb
GWG_49.pdb
G

In [120]:
import numpy as np
dataob=open('score_interface_filter1.txt','r')
alldict={}
for line in dataob.readlines():
    line=line.strip()
    infor=line.split()
    name=infor[0].split('_')[0]
    score=infor[1]
    alldict[name]=[]
dataob=open('score_interface_filter1.txt','r')
for line in dataob.readlines():
    line=line.strip()
    infor=line.split()
    name=infor[0].split('_')[0]
    score=float(infor[1])
    alldict[name].append(score)
sdict={}
for key in alldict:   
    sscore=np.min(alldict[key])
    sdict[key]=sscore
dict_ob=sorted(sdict.items(),key=lambda item:item[1])
wf=open('score_interface_filter_set1.txt','w')
for aa in dict_ob:
    wf.write(aa[0]+'\t'+str(aa[1])+'\n')
wf.close()

In [105]:
import numpy as np
dataob=open('all_score.txt','r')
alldict={}
for line in dataob.readlines():
    line=line.strip()
    infor=line.split()
    name=infor[0].split('_')[0]
    score=infor[1]
    alldict[name]=[]
dataob=open('all_score.txt','r')
for line in dataob.readlines():
    line=line.strip()
    infor=line.split()
    name=infor[0].split('_')[0]
    score=float(infor[1])
    alldict[name].append(score)
sdict={}
for key in alldict:   
    sscore=np.min(alldict[key])
    sdict[key]=sscore
dict_ob=sorted(sdict.items(),key=lambda item:item[1])
wf=open('all_score_set.txt','w')
wf2=open('all.seq','w')
bb=0
for aa in dict_ob:
    bb+=1
    wf2.write('>'+str(aa[1])+'_'+str(bb)+'\n'+aa[0]+'\n')
    wf.write(aa[0]+'\t'+str(aa[1])+'\n')
wf.close()
wf2.close()

In [106]:
from pdbfixer.pdbfixer import PDBFixer

In [138]:
cd /home/dongdong/SCR/PD1/3_all

/scratch/gpfs/dongdong/PD1/3_all


In [142]:
seq='GAVLIPFYWSTCMNQDEKRH'
for i in range(20):
    name='allfasta_'+str(i)+'.fasta'
    wf=open(name,'w')
    for j in range(20):
        for k in range(20):
            wf.write(seq[i]+seq[j]+seq[k]+'\n')
wf.close()

In [145]:
for i in range(1,20):        
    name='allfasta_'+str(i)+'.fasta'
    filename='Pep_Mod'+str(i)+'.bash'
    resultsname='results'+str(i)
    os.system("sed -i 's/results/%s/g' %s " %(resultsname,filename))
    os.system("sed -i 's/allfasta.fasta/%s/g' %s " %(name,filename))

In [146]:
for i in range(0,20):  
    filename='run'+str(i)+'.sh'
    name='Pep_Mod'+str(i)+'.bash'
    os.system("sed -i 's/Pep_Mod.bash/%s/g' %s " %(name,filename))

In [188]:
cd /home/dongdong/SCR/PD1/3/PD1_results/

/scratch/gpfs/dongdong/PD1/3/PD1_results


In [149]:
import Bio

In [7]:
import pandas as pd
from biopandas.pdb import PandasPdb
def ligand_center(name):
    ppdb = PandasPdb().read_pdb(name)
    xc=ppdb.df['ATOM'][ppdb.df['ATOM']['chain_id']=='P']['x_coord']
    yc=ppdb.df['ATOM'][ppdb.df['ATOM']['chain_id']=='P']['y_coord']
    zc=ppdb.df['ATOM'][ppdb.df['ATOM']['chain_id']=='P']['z_coord']
    xmean=np.mean(np.array(xc))
    ymean=np.mean(np.array(yc))
    zmean=np.mean(np.array(zc))
    return xmean, ymean, zmean

In [193]:
dirname='/home/dongdong/SCR/PD1/3/PD1_results/'
rf=open(dirname+'sorted.txt','r')
wf=open(dirname+'center_of_mass.txt','w')
for line in rf.readlines()[1:]:
    line=line.strip()
    peptide=line.split()[0]
    score=line.split()[1]
    wf.write(line+'    ')
    peptidefile=dirname+'docked_pdb/'+peptide+'.pdb'
    print
    x, y, z = ligand_center(peptidefile)
    wf.write(str(x)+'    '+str(y)+'    '+str(z)+'\n')
wf.close()



In [211]:
import sklearn.cluster as cluster
rf=open(dirname+'center_of_mass.txt','r')
allxyz=[]
for line in rf.readlines():
    temp=[]
    line=line.strip()
    temp.append(float(line.split()[2]))
    temp.append(float(line.split()[3]))
    temp.append(float(line.split()[4]))
    allxyz.append(np.array(temp))
allxyz=np.array(allxyz)
print(allxyz)
ncluster=15
cls=cluster.AgglomerativeClustering(n_clusters = ncluster)
cls.fit(allxyz)
np.savetxt('cluster.dat', cls.labels_, fmt = '%d')

[[ 11.16125532  36.57038298 105.24844681]
 [ 12.006       36.17691489  96.58455319]
 [ 12.01951064  36.32991489  96.34187234]
 ...
 [  9.66658537  36.36721951  97.87339024]
 [  9.57534146  37.34670732  96.3374878 ]
 [  9.60657143  37.18065714  96.67391429]]


In [218]:
rf=open(dirname+'center_of_mass.txt','r')
lines=rf.readlines()
cls_label=np.loadtxt('cluster.dat')
for i in range(ncluster):
    xyzfile='xyz_c'+str(i)+'.xyz'
    allinfo='cls_info'+str(i)+'.dat'
    wf=open(xyzfile,'w')
    wf2=open(allinfo,'w')
    wf.write(str(30)+'\n c'+str(i)+'\n')
    n=0
    for ii in range(len(cls_label)):
        if n<30 and cls_label[ii]==i:
            wf2.write(lines[ii].strip()+'    '+str(i)+'\n')
            wf.write('  C        %f        %f        %f\n' %(allxyz[ii][0], allxyz[ii][1], allxyz[ii][2]))
            n+=1
    wf.close()
    wf2.close()
            


In [216]:
rf=open(dirname+'center_of_mass.txt','r')
cls_label=np.loadtxt('cluster.dat')
wf=open('new_center_of_mass.txt','w')
i=0
for line in rf.readlines():
    line=line.strip()
    wf.write(line+'    '+str(cls_label[i])+'\n')
    i+=1
wf.close()

In [1]:
cd /home/dongdong/SCR/PD1/3_all_results

/scratch/gpfs/dongdong/PD1/3_all_results


In [10]:
import numpy as np
for i in range(20):
    print(i)
    dirname = '/home/dongdong/SCR/PD1/3_all_results/results_%d_sh/vs/PD1_sh/Results/' %i
    rf=open(dirname+'sorted.txt','r')
    wf=open(dirname+'center_of_mass.txt','w')
    for line in rf.readlines()[1:]:
        line=line.strip()
        peptide=line.split()[0]
        score=line.split()[1]
        wf.write(line+'    ')
        peptidefile=dirname+'docked_pdb/'+peptide+'.pdb'
        x, y, z = ligand_center(peptidefile)
        wf.write(str(x)+'    '+str(y)+'    '+str(z)+'\n')
    wf.close()

0


/home/dongdong/software/anaconda3/envs/py3.6/lib/python3.6/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/dongdong/software/anaconda3/envs/py3.6/lib/python3.6/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [12]:
import os
for i in range(20):
    print(i)
    dirname = '/home/dongdong/SCR/PD1/3_all_results/results_%d_sh/vs/PD1_sh/Results/' %i
    filename = dirname+'center_of_mass.txt'
    outfile = '/home/dongdong/SCR/PD1/3_all_results/center_of_mass%d.txt' %i
    os.system('cp %s %s' %(filename, outfile))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [1]:
import sklearn.cluster as cluster

In [4]:
cd /home/dongdong/SCR/PD1/3_all_results

/scratch/gpfs/dongdong/PD1/3_all_results


In [9]:
import sklearn.cluster as cluster
import numpy as np
rf=open('all_new_center_of_mass.txt','r')
allxyz=[]
for line in rf.readlines():
    temp=[]
    line=line.strip()
    temp.append(float(line.split()[2]))
    temp.append(float(line.split()[3]))
    temp.append(float(line.split()[4]))
    allxyz.append(np.array(temp))
allxyz=np.array(allxyz)

ncluster=15
cls=cluster.MiniBatchKMeans(n_clusters = ncluster)
cls.fit(allxyz)
np.savetxt('all_cluster.dat', cls.labels_, fmt = '%d')

In [11]:
rf=open('all_new_center_of_mass.txt','r')
lines=rf.readlines()
cls_label=np.loadtxt('all_cluster.dat')
for i in range(ncluster):
    xyzfile='xyz_c'+str(i)+'.xyz'
    allinfo='cls_info'+str(i)+'.dat'
    wf=open(xyzfile,'w')
    wf2=open(allinfo,'w')
    wf.write(str(200)+'\n c'+str(i)+'\n')
    n=0
    for ii in range(len(cls_label)):
        if n<200 and cls_label[ii]==i:
            wf2.write(lines[ii].strip()+'    '+str(i)+'\n')
            wf.write('  C        %f        %f        %f\n' %(allxyz[ii][0], allxyz[ii][1], allxyz[ii][2]))
            n+=1
    wf.close()
    wf2.close()

In [14]:
import os
for i in range(15):
    filename='cls_info%d.dat' %i
    rf=open(filename,'r')
    dirname='cls%d' %i
    os.mkdir(dirname)
    n=0
    for line in rf.readlines():
        n+=1
        line = line.strip()
        pdbname=line.split()[0]+'.pdb'
        os.system('cp all/%s %s/%d_%s' %(pdbname,dirname,n,pdbname))
    rf.close()
        

In [22]:
all_score=[]
for i in range(20):
    name='sort%d.txt' %i
    rf=open(name,'r')
    lines=rf.readlines()[1:]
    for line in lines:
        line=line.strip()
        line=line.split()
        all_score.append(line)

In [23]:
all_score

[['GYW_9', '-9.3'],
 ['GFR_6', '-8.7'],
 ['GWW_7', '-8.6'],
 ['GHW_25', '-8.5'],
 ['GYW_19', '-8.5'],
 ['GHY_4', '-8.4'],
 ['GRW_34', '-8.4'],
 ['GHY_10', '-8.3'],
 ['GHY_26', '-8.3'],
 ['GHY_30', '-8.2'],
 ['GQH_3', '-8.2'],
 ['GTW_34', '-8.2'],
 ['GWW_19', '-8.2'],
 ['GWY_23', '-8.2'],
 ['GWY_36', '-8.2'],
 ['GYY_39', '-8.2'],
 ['GFR_25', '-8.1'],
 ['GFY_22', '-8.1'],
 ['GHN_15', '-8.1'],
 ['GKW_34', '-8.1'],
 ['GQQ_29', '-8.1'],
 ['GWF_13', '-8.1'],
 ['GWH_36', '-8.1'],
 ['GWK_36', '-8.1'],
 ['GWQ_25', '-8.1'],
 ['GWR_36', '-8.1'],
 ['GWW_32', '-8.1'],
 ['GYF_20', '-8.1'],
 ['GYY_21', '-8.1'],
 ['GYY_31', '-8.1'],
 ['GFW_17', '-8.0'],
 ['GFY_25', '-8.0'],
 ['GIW_26', '-8.0'],
 ['GNW_34', '-8.0'],
 ['GRE_10', '-8.0'],
 ['GRY_5', '-8.0'],
 ['GTW_20', '-8.0'],
 ['GWF_24', '-8.0'],
 ['GWW_15', '-8.0'],
 ['GWW_36', '-8.0'],
 ['GYW_22', '-8.0'],
 ['GYW_6', '-8.0'],
 ['GFW_25', '-7.9'],
 ['GFY_38', '-7.9'],
 ['GHW_20', '-7.9'],
 ['GHY_24', '-7.9'],
 ['GKW_18', '-7.9'],
 ['GRF_3', '-7.9'],


In [30]:
new_sore=sorted(all_score,key=lambda r:float(r[1]))

In [35]:
wf=open('all_new_score.cs','w')
for nn in new_sore:
    wf.write(str(nn[0])+'\t'+str(nn[1])+'\n')
wf.close()

In [8]:
all_score=[]
rf=open('all_center_of_mass.txt','r')
lines=rf.readlines()
for line in lines:
        line=line.strip()
        line=line.split()
        all_score.append(line)
new_sore=sorted(all_score,key=lambda r:float(r[1]))
wf=open('all_new_center_of_mass.txt','w')
for nn in new_sore:
    for ii in nn:
        wf.write(str(ii)+'    ')
    wf.write('\n')
wf.close()