In [1]:
cd /home/dongdong/SCR/trpcage.run6cv/000_kappa100

/scratch/gpfs/dongdong/trpcage.run6cv/000_kappa100


In [3]:
import numpy as np
import subprocess as sp

tail=0.0
cv_dih_dim = 6
data = np.loadtxt ("plm.res.out")
data = data[:,1:]
kk=np.loadtxt('kappa.out');
cc=np.loadtxt('centers.out');
nframes=data.shape[0]
ndih_values=data.shape[1]
if cv_dih_dim is not None :
    ndih_values = cv_dih_dim

In [6]:
n_10ps_block = 1000   # since we have 10ns data, we have 1000 10ps blocks.
nstep_10ps = nframes // n_10ps_block   # each 10ps contains nsteps.
avgins = np.average (np.reshape(data[:n_10ps_block*nstep_10ps,:],[n_10ps_block,nstep_10ps,-1]), axis = 1)

In [11]:
avgins1 = np.mod(avgins - np.reshape(cc,[1,-1]) + np.pi * 5., np.pi * 2.) - np.pi

In [40]:
avgins1

array([[-0.01595623,  0.17547823,  0.11043491,  0.17483568, -0.04939829,
        -0.06366871],
       [-0.00457319,  0.1659359 ,  0.08310578,  0.1406836 , -0.03377753,
        -0.03101028],
       [-0.01470434,  0.17970355,  0.08330535,  0.16738147,  0.0338287 ,
        -0.03374837],
       ..., 
       [ 0.05419704,  0.13337159,  0.2150767 , -0.06588519,  0.13632498,
        -0.00569304],
       [ 0.06123131,  0.09439649,  0.27591054, -0.05182752,  0.09164166,
        -0.04225186],
       [ 0.03977898,  0.14836554,  0.207654  , -0.02853781,  0.14266848,
        -0.02426545]])

In [13]:
avgins1 = avgins - np.reshape(cc,[1,-1])

In [15]:
ffs = avgins1 * np.reshape(kk,[1,-1])

In [41]:
len(ffs)

1000

In [17]:
ff_mean = np.mean(ffs,axis=0)

In [18]:
ff_mean

array([  1.11413912,   9.55071967,  16.17132295,   5.01626621,
         8.76866456,  -4.01821123])

In [30]:
ff_magnitude = (ff_mean**2)**0.5

In [31]:
ff_magnitude

array([  1.11413912,   9.55071967,  16.17132295,   5.01626621,
         8.76866456,   4.01821123])

In [37]:
print("relative stat error of 10ps mdrun: ")
print(np.std(ffs,axis=0)/ff_magnitude)

relative stat error of 10ps mdrun: 
[ 3.10689176  0.4903704   0.51442813  1.39390913  1.10582046  0.57939052]


In [33]:
ffs_tmp = np.mean(np.reshape(ffs,[500,2,-1]), axis=1)
np.std(ffs_tmp,axis=0)/ff_magnitude

array([ 3.06652953,  0.46751735,  0.47753946,  1.34702626,  1.08359892,
        0.52299123])

In [39]:
ffs_tmp = np.mean(np.reshape(ffs,[500,2,-1]), axis=1)
np.std(ffs_tmp,axis=0)/ff_magnitude

array([ 3.06652953,  0.46751735,  0.47753946,  1.34702626,  1.08359892,
        0.52299123])

In [38]:
ffs_tmp = np.mean(np.reshape(ffs,[5,200,-1]), axis=1)
np.std(ffs_tmp,axis=0)/ff_magnitude

array([ 1.94069085,  0.22137436,  0.23843049,  0.84802056,  0.63060279,
        0.16095106])